image: prusa/oe

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
   - ssh-keyscan -p 22443 gitlab.webdev.prusa3d.com >> ~/.ssh/known_hosts

build:
  stage: build
  script: 
    - cd /builds/hw/a64/oe
    - source oe-init-build-env
    - bitbake sla-update-bundle sla-image-dev
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb
      - build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.etc.ext4
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.rootfs.wic.xz
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.rootfs.wic.bmap
      - build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1.manifest
      - build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1.manifest
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1.manifest
      - changelog.txt

deploy:
  stage: deploy
  when: manual
  script:
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ./
    - BASE=$(ls sla-update-bundle-prusa64-sl1-*.raucb | sed 's/sla-update-bundle-prusa64-sl1-\(v.*\)-[0-9]*.raucb/\1/')
    - echo ${BASE}
    - mv sla-update-bundle-prusa64-sl1-*.raucb ${BASE}.raucb
    - mv changelog.txt ${BASE}.changelog.txt
    - lftp -c "set ssl:verify-certificate 06:02:1F:B9:B1:FD:7E:6E:B6:39:97:69:EF:A2:02:46:D0:19:BB:88; open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST}; put -O deploy ${BASE}.raucb; put -O deploy ${BASE}.changelog.txt"

  dependencies:
    - build
