image: prusa/oe

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - echo "$DEV_DEPLOY_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - cat ~/.ssh/known_hosts
  - mkdir -p build/conf && touch build/conf/auto.conf
  - sed -i -e '/SSTATE_DIR/d' -e '/DL_DIR/d' build/conf/auto.conf
  - cat build/conf/auto.conf

cache:
  key: build-cache
  paths:
    - build/downloads
    - build/cache
    - build/sstate-cache
 
build:raucb:
  stage: build

  only: 
    - tags
    - merge_requests
    - web

  script:
    - cat build/conf/auto.conf
    - source oe-init-build-env
    - bitbake sla-update-bundle
    - cd ..
    - BASE=$(git describe --dirty)
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ${BASE}.raucb
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.etc.ext4 ${BASE}.etc.ext4
    - mv build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest ${BASE}.initramfs.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest ${BASE}.manifest
    - mv changelog.txt ${BASE}.changelog.txt
    - mv known-issues.txt ${BASE}.known-issues.txt

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.raucb
      - ./*.etc.ext4
      - ./*.manifest
      - ./*.changelog.txt
      - ./*.known-issues.txt

build:tools:
  stage: build
  when: manual

  dependencies: []    

  only:
    - tags
    - merge_requests
    - web

  script:
    - source oe-init-build-env
    - bitbake sla-image-dev sla-bootstrap
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic
    - cd ..
    - BASE=$(git describe --dirty)
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.wic.xz ${BASE}.devsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.wic.bmap ${BASE}.devsd.bmap
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.manifest ${BASE}.devsd.manifest
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.xz ${BASE}.bootstrapsd.xz
    - mv build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.bmap ${BASE}.bootstrapsd.bmap

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - ./*.devsd.*
      - ./*.bootstrapsd.*

deploy:raucb:
  stage: deploy
  when: manual
  cache: {}
  
  dependencies:
    - build:raucb

  only:
    - tags
    - merge_requests
    - web

  script:
    - BASE=$(git describe --dirty)
    - >
        lftp -c "
        set ssl:verify-certificate ${DEPLOY_FTP_FINGERPRINT};
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEST} ${BASE}.raucb;
        put -O ${DEST} ${BASE}.changelog.txt;
        put -O ${DEST} ${BASE}.known-issues.txt;
        "
    - echo "put ${BASE}.raucb" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${BASE}.changelog.txt" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${BASE}.known-issues.txt" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}

deploy:tools:
  stage: deploy
  when: manual
  cache: {}

  dependencies:
    - build:tools

  only:
    - tags
    - merge_requests
    - web

  script:
    - BASE=$(git describe --dirty)
    - echo "put ${BASE}.devsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${BASE}.devsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${BASE}.bootstrapsd.xz" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
    - echo "put ${BASE}.bootstrapsd.bmap" | sftp ${DEV_DEPLOY_USER}@${DEV_DEPLOY_HOST}
