image: prusa/oe

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: "normal"

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - cat ~/.ssh/known_hosts
  - mkdir -p build/conf && touch build/conf/auto.conf
  - sed -i -e '/BB_NUMBER_THREADS/d' -e '/PARALLEL_MAKE/d' -e '/SSTATE_DIR/d' -e '/PRSERV_HOST/d' build/conf/auto.conf
  - echo 'SSTATE_DIR = "/sstate-cache/noprserv"' >> build/conf/auto.conf

build:
  stage: build

  only: 
    - tags
    - merge_requests
    - web

  script:
    - cat build/conf/auto.conf
    - source oe-init-build-env
    - bitbake sla-update-bundle sla-image-dev
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb
      - build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.etc.ext4
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.rootfs.wic.xz
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.rootfs.wic.bmap
      - build/tmp/deploy/images/prusa64-sl1/sla-initramfs-prusa64-sl1-*.manifest
      - build/tmp/deploy/images/prusa64-sl1/sla-image-prusa64-sl1-*.manifest
      - build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.manifest
      - changelog.txt
      - known-issues.txt

bootstrap:
  stage: build
  when: manual

  dependencies: []    

  only:
    - tags
    - merge_requests
    - web

  script:
    - source oe-init-build-env
    - bitbake sla-bootstrap
    - xz -T0 --verbose tmp/deploy/images/prusa64-sl1/*.rootfs.wic

  artifacts:
    expire_in: 1 week
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.xz
      - build/tmp/deploy/images/prusa64-sl1/sla-bootstrap-prusa64-sl1-*.rootfs.wic.bmap

deploy:
  stage: deploy
  when: manual
  
  dependencies:
    - build

  only:
    - tags
    - merge_requests
    - web

  script:
    - mv build/tmp/deploy/images/prusa64-sl1/sla-update-bundle-prusa64-sl1-*.raucb ./
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.wic.xz ./
    - mv build/tmp/deploy/images/prusa64-sl1/sla-image-dev-prusa64-sl1-*.wic.bmap ./
    - BASE=$(ls sla-update-bundle-prusa64-sl1-*.raucb | sed 's/sla-update-bundle-prusa64-sl1-\(.*\)-[0-9]*.raucb/\1/')
    - echo ${BASE}
    - mv sla-update-bundle-prusa64-sl1-*.raucb ${BASE}.raucb
    - mv changelog.txt ${BASE}.changelog.txt
    - mv known-issues.txt ${BASE}.known-issues.txt
    - mv sla-image-dev-prusa64-sl1-*.wic.xz ${BASE}.devsd.xz
    - mv sla-image-dev-prusa64-sl1-*.wic.bmap ${BASE}.devsd.bmap
    - >
        lftp -c "
        set ssl:verify-certificate ${DEPLOY_FTP_FINGERPRINT};
        open -u ${DEPLOY_FTP_USER},${DEPLOY_FTP_PASS} ${DEPLOY_FTP_HOST};
        put -O ${DEST} ${BASE}.raucb;
        put -O ${DEST} ${BASE}.changelog.txt;
        put -O ${DEST} ${BASE}.known-issues.txt;
        put -O ${DEST} ${BASE}.devsd.xz;
        put -O ${DEST} ${BASE}.devsd.bmap;
        "
